### ISSUE TITLE
Don't start playing audio until a key is pressed

### ISSUE THREAD

**Issue by duncangeere** [loudnumbers/ufo#3]
After the script loads, the screen should display something like:
"Press K3 to receive audio signals".

When K3 is pressed, audio should begin.

It would be fairly easy to hook this up to `engine_amp` but is there a better way of not triggering notes until the user is ready @jaseknighter?

**Comment by duncangeere** [comment]
I've implemented a fairly naive on/off version of this with `engine_amp` for now in https://github.com/loudnumbers/ufo/commit/69037e59cf8f3249b7fb2fd6f524f0379217a4bd, but it would be nice to either fade in/out or have it stop generating new notes when you press the button and let existing ones fade out.

**Comment by jaseknighter** [comment]
if you call `engine.stop()` it'll fade things out. :)

i'll figure out a way to have the engine stopped at load...shouldn't be complicated.

**Comment by duncangeere** [comment]
Great! As soon as you've sorted out having the engine stopped on load, I'll add `engine.start()` and `engine.stop()` commands on K3.

**Comment by jaseknighter** [comment]
if you feel like it, try removing `.play()` from line 151 in the *Engine_SupSawEV.sc* file so the line just looks like `    });`

then you can start it up from a key press by calling `engine.start()`

**Comment by duncangeere** [comment]
Removing `.play()` made it not start playing automatically 👍 
Adding `engine.start()` worked once I edited the .sc file to say `routine.play();` rather than `routine.value();` which only played one note and then stopped again 👍 
Tweaking it to `engine.start(0)` and `engine.stop(0)` got rid of another annoying warning 👍 
Finally I had a problem where it wouldn't start again after it had been stopped. Adding a `routine.reset()` before the `routine.play()` in the .sc file fixed that one! 👍 

So I think this is sorted!
