### ISSUE TITLE
Bass notes are a bit loud

### ISSUE THREAD

**Issue by duncangeere** [loudnumbers/ufo#4]
Low notes quite easily clip/distort, going over the max in the levels window on Norns - in my testing this seems to happen below middle C.

**Comment by jaseknighter** [comment]
in the supercollider code, line 85 has a limiter that has been commented out. you could try uncommenting it and seeing if that sounds better to you.

here is the api for the limiter if you want to mess with it: https://doc.sccode.org/Classes/Limiter.html

**Comment by duncangeere** [comment]
Uncommenting it didn't seem to make any difference, nor did turning it down from 0.4 to 0.3. I'll poke around with the API a bit more!

**Comment by jaseknighter** [comment]
cool, this might also be something to ask about in the sc channel on the norns discord. i've never implemented a limiter before so there might be a better way to do this.

**Comment by duncangeere** [comment]
This seems sorted now!
